# Generated by Django 3.2.9 on 2022-08-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
