# Generated by Django 3.2.9 on 2022-08-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_rename_category_product_categary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
