# Generated by Django 3.2.9 on 2022-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='uploads/offer/')),
            ],
        ),
    ]
