# Generated by Django 3.2.9 on 2022-08-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20220809_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uname',
        ),
    ]
