# Generated by Django 3.2.9 on 2022-08-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20220809_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
