# Generated by Django 3.2.9 on 2022-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_customer_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reat_password',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
