# Generated by Django 3.2.9 on 2022-08-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_customer_reat_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reat_password',
        ),
    ]
