# Generated by Django 3.2.9 on 2022-08-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
