# Generated by Django 3.2.9 on 2022-08-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_remove_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
