# Generated by Django 3.2.9 on 2022-08-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='statu',
        ),
    ]
