# Generated by Django 3.2.9 on 2022-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_rename_status_order_statu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='statu',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
