# Generated by Django 3.2.9 on 2022-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0026_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(upload_to='uploads/productDetails/'),
        ),
    ]
