# Generated by Django 3.2.9 on 2022-09-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0028_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='sellprice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sellprice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
