# Generated by Django 3.2.9 on 2022-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_auto_20220901_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=int),
        ),
    ]
