# Generated by Django 3.2.9 on 2022-09-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellprice',
            field=models.IntegerField(blank=True, default=int),
        ),
    ]
