# Generated by Django 3.2.9 on 2022-09-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0031_auto_20220901_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellprice',
            field=models.IntegerField(blank=True),
        ),
    ]
