# Generated by Django 3.2.9 on 2022-09-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0032_alter_product_sellprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellprice',
            field=models.IntegerField(),
        ),
    ]
