# Generated by Django 3.2.9 on 2022-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0033_alter_product_sellprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
